server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:h2:mem:///point-db?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    pool:
      initial-size: 20
      max-size: 80
      max-idle-time: 30m
      validation-query: SELECT 1
      max-acquire-time: 3s
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 100
          max-idle: 30
          min-idle: 10
          max-wait: 3000ms

logging:
  level:
    com.example.wehomework: INFO
    org.springframework.r2dbc: WARN
    org.springframework.data.redis: WARN
